### ISSUE TITLE
TextLoaderUI not working correctly

### ISSUE THREAD

**Issue by simlei** [jcryptool/crypto#173] opened 2018-04-04 12:22 UTC
Problem seems to lie with org.jcryptool.crypto.ui/src/org/jcryptool/crypto/ui/textloader/ui/wizard/loadtext/UIInputTextWithSource.java 

![image](https://user-images.githubusercontent.com/982379/38307173-31e70818-3813-11e8-9047-a5879a19d0a9.png)
![image](https://user-images.githubusercontent.com/982379/38307179-3640ef00-3813-11e8-9324-6875bb62f259.png)

According to @tassadarius ``isEditorAvailable()`` returns true even when "no suitable editor is opened" in e.g. the substitution analysis plugin when entering custom text.
further information & reproduction where and how this manifests would be appreciated

**Comment by tassadarius** [comment] 2018-04-04 17:36
## How to reproduce

**1. Start an instance of a plugin which uses TextLoaderUI and close all other views .**

![0_full-window](https://user-images.githubusercontent.com/22643766/38323428-81e00426-383d-11e8-82d1-d3d39369d791.png)

**2. Load the text. The function getDefaultContent ( ) will eventually check if Editors are available by calling following function.**

![1_get-function](https://user-images.githubusercontent.com/22643766/38323508-ba6cfb78-383d-11e8-826b-8cac70b77cde.png)

**As we can see in the variable field there is an entry in this list, but there is not really an editor opened.**

![2_returned-editor](https://user-images.githubusercontent.com/22643766/38323538-ce8a54e8-383d-11e8-8b70-d60f8071ea6e.PNG)

**The function will take this branch:**

![3_function-branch](https://user-images.githubusercontent.com/22643766/38323574-f044d95a-383d-11e8-99e1-9a7a48a30b2b.png)

**And eventually run into a NullPointer somewhere in there.**

![4_stack-trace](https://user-images.githubusercontent.com/22643766/38323940-0fb5ffc0-383f-11e8-9666-c9394a2cb487.png)

**Comment by simlei** [comment] 2018-04-04 18:09
Thanks!

**Comment by simlei** [comment] 2018-04-04 18:42
@tassadarius  Could not reproduce.

> 2. Load the text

What was the text you loaded? I tried with the predefined text that a new editor shows, and with no editor opened at all. Neither misbehaved, everything worked as expected.

**Comment by tassadarius** [comment] 2018-04-04 18:46
@simlei The error happens before loading any text (on button press to open the dialog). Sometimes it still works when all editors are closed yes. I usually play around a little bit with opening and closing files in the editor and then the error occurs.

**Comment by simlei** [comment] 2018-04-04 21:02
OK then I definitely have different behaviour. The weekly build works o.k. also. I downloaded and tested with https://github.com/jcryptool/core/releases/tag/Weekly-Build-31.03.2018 -- loading a text is possible. 

Could you check if the current weekly build works for you? Then we know if it is an issue of your local repository or not.

**Comment by tassadarius** [comment] 2018-04-06 21:09
Reproducing the error on a clean installation proved harder than I thought, but is possible, so the bug is in the latest weekly build. Reproducing the bug is not consistent, and it is quite tricky, but it seems to have something to do with the visual.huffman plugin. A second try for a reproduce:

1. Open any plugin and close all other views so that only the "Shared Area" and the plugin remain. I chose analysis.substition. The plugin should be full screen and the "Shared Area" minimized.

2. Now open the Huffman plugin.

3. Try to restore or maximize the Shared Area again. The icon should disappear now and not open. (I cannot tell if this already throws an exception, as it seems already a contributing part to the bug).

4. Open a "New Sample File in Texteditor" - it should work fine with the substition analysis, but you cannot actually open the editor anymore since the Shared Area disappeared. 

5. If you choose to Window->Reset you will get to the Default view, except the Editor shows an error message instead of an opened file. (I can post the stack trace if you want).

6. Open a TextLoader plugin, I chose substitution again and press on "Load Text". Now the TextLoader should not be not working correctly (All 3 radio buttons enabled, but none preselected. Load from editor does nothing, putting in own text is allowed but the result not usable).

Seems pretty unusual and elaborate to reproduce, but me and @be4 got this bug after working with the Huffman plugin. I'm curios if it works for you.

**Comment by simlei** [comment] 2018-04-08 22:11
Hi, 
spot on reproduction steps :) I would not have found that on my own.
Well we seem to have a cascade of things failing. Let's see:
1) The shared area crashed (your point no. 3)
2) Editor display misbehaves afterwards. The editor backend actually seems tro try its best to carry on as you observed, in spite of having no means of display.
3) Perspective reset (probably in extension, perspective setup) seems to fail then, probably because of the shared area thing, but could be something else, too. _My money is on that that the editor that was leaked from before (your step 4) but on some now invalid parent shared area reference ("corpse", being a stale resource pointer)._ Not sure though, had not enough time to really dig into it yet.

Well and then we have an editor part at the end of that cascade that is not actually an editor, but really an exception display. The poor substitution analysis/textloader ui panics, because afaik nowhere in the code an editor is modelled to be an exception display.
Two ways to see it: a) the textloader code is faulty because it doesn't handle that and b) the damage was already done by having the editor display such exception.

I'd go with b) because solving the editor, shared area and perspective reset problem will also solve the textloader problem _completely_ (as I have not found another way to push the textloader into panic than giving it an exception-display-editor). I would go so far to say it would be __misguided to fix the problem tackling the textloader first__; we would still have broken editor and perspective issues, what's the fun in that. Especially, video number 3 demonstrates that when we fix the faulty editor showing up (minimally speaking of course) the Textloader UI continues to work as expected. 

Does this reasoning match your experience with the issue? I'm going on a bit more already on the problem. Please do comment if you think I missed some of the problem! @tassadarius

To me, there seem to be 2 things actually to fix:

- Probably a bug in the eclipse framework: shared area disappears and causes problems, leaving the only way out a perspective reset. This alone is an issue of its own worth fixing I think. My money is this being an eclipse framework bug. Research necessary, diving into our stacktraces and probably eclipse bugtrackers. However, it's rather hard to reproduce...
- On perspective reset, the last opened editor may be invalid and restoring it could leave to a 'dead editor' with a stacktrace in it. We don't want that on a critical safeguard like "perspective reset"; rather dump the exception into the log, and leave the editor closed. As can be observed in video no. 2, opening the editor by hand thereafter works and everthing is pretty! So, how about just fixing the perspective reset to work properly and rather not float editor corpses but log the stacktrace and silently try to reopen in the default, fresh shared area, ask the user, or silently show no editor?

Videos of what i have got in my tries. I'm pretty positive this is exactly what you had. Note the recovery in video 3 though.
- 1: point of failure https://www.dropbox.com/s/hjqklsedxe7qkto/jct_failing.mp4?dl=0
- 2: somehow here it works https://www.dropbox.com/s/gfkvlkf94qcpfgx/jct_working.mp4?dl=0
- 3: demonstration of being able to recover when ignoring the faulty editor: https://www.dropbox.com/s/mnrlpxusbq4ql9l/jct_fail_then_recovery.mp4?dl=0

Again, very nice that this is now a stably reproducible thing!! Thanks!
I think we had this issue in the past but were never able to really put our finger on it.

**Comment by simlei** [comment] 2018-04-08 22:51
The only mentions of problems with the shared area I could find were from 2011 and resolved. I think they are not related to our issue. I think it may actually be a problem with the custom implementation editors for JCT, but I remain unsure.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=347471
https://bugs.eclipse.org/bugs/show_bug.cgi?id=349482
However, activity in the eclipse community seems to have gone down in the past years, and I also remember issues marked as "fixed" when they really weren't. Plus, I can't really imageine how JCT code could bring forth this shared area misbehavior.

**Comment by tassadarius** [comment] 2018-04-09 16:25
Seems to cover everything pretty well. Only thing I am wondering is why this seems to be a problem only with certain plugins.

**Comment by simlei** [comment] 2018-04-09 19:48
I'll make some time next weekend to investigate more.
Now that you mention it; which other plugins cause it @tassadarius ? I thought, the Huffman-plugin-choice was arbitrary...

**Comment by grthor** [comment] 2019-07-13 16:08
Could not reproduce the error. Does the problem still occur @tassadarius ?
If it does not occur I would close the issue.

**Comment by tassadarius** [comment] 2019-07-28 13:02
With build 1.0.0 20190706 I could not reproduce anymore. I don't think someone patched it on purpose but as long as its fixed its good. I think we can close the issue

**Closed** 2019-07-29 11:55 UTC
Labels: Bug
